### ISSUE TITLE
Ability to cancel booked reps

### ISSUE THREAD

**Issue by mxk16sbu** [xsd08tfu/sw-bug-tracker#232]
- [x] Cancel but not allow reallocation

## What feature are you looking for? ##
If we could cancel someones who's been booked ourselves, that would be really handy. Then possibly, could we replace them with those on the list rather than making a new job and posting it out again? I'm not sure if this has been spoken about before, apologies if so!!

**Comment by xsd08tfu** [comment]
Hi Matt,

The problem here comes that the onus should be on workers to cancel their shift themselves, and based on feedback from both Staff and Workers we shouldn't automatically reallocate within the last 48 hours as they feel pressured in to working a shift even if they can't. 

However I am going to work on the messaging with workers about cancelling shifts, and make it easier for people to indicate if they are available as a reserve or not.
